config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 root 'donators#home'

 resources :donators do
 	member  do 
  		put :change
  		get 'search'
  	end
 end
 
 resources :receivers do
 	member do
 		put :change
 		get 'search'
 	end
 end

 resources :donates do
 	member do
 		put :change
 		get 'search'
 	end
 end


 get 'new' => 'donators#new'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/donate.rb
class Donate < ApplicationRecord
end

app/models/donator.rb
class Donator < ApplicationRecord

def self.search(search)
  if search
    Donator.where('nama LIKE ?', "%#{search}%")
  else
    Donator.all
  end
end


end

app/models/receiver.rb
class Receiver < ApplicationRecord


def self.search(search)
  if search
    Receiver.where('nama LIKE ?', "%#{search}%")
  else
    Receiver.all
  end
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/donates_controller.rb
class DonatesController < ApplicationController


before_action :set_donate, only: [:show, :edit, :update, :destroy, :change]

	respond_to :html

	def index
		
	end

	def update
		
	end

	def show
		
	end

	def edit
		
	end

	def home
		
	end

	def new
		@donate = Donate.new
    	respond_with(@donate)
		
	end

	def create
		
	end

	def change
		
	end

	def destroy
		
	end

	private

		def set_donate
	    
	      @donate = Donates.find(params[:id])

	    end


    # Never trust parameters from the scary internet, only allow the white list through.
		   def donate_params
		     params.require(:donate).permit(:donatur, :tgl_donasi, :dana, :barang, :besar_dana)
		   end


end

app/controllers/donators_controller.rb
class DonatorsController < ApplicationController
  
  before_action :set_donator, only: [:show, :edit, :update, :destroy, :change]

	respond_to :html


  def home
  end

  def new
  	@donator = Donator.new
    respond_with(@donator)
  end

  def edit
  end

  def delete
  	
  end

  def destroy
  	@donator.destroy
    respond_to do |format|
      format.html { redirect_to donators_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def create
  	@donator = Donator.new(donator_params)

    @donator.save
    respond_with(@donator)
  end

  def show
  	
  end

  def change
    @donator.update_attributes(state: params[:state])
    respond_to do |format|
      format.html {redirect_to donators_path, notice: "Donator Update"}
    end
  end

  def update
    respond_to do |format|
      if @donator.update(donator_params)
        format.html { redirect_to @donator, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @donator }
      else
        format.html { render :edit }
        format.json { render json: @donator.errors, status: :unprocessable_entity }
      end
    end
  end


  def index
  	@donators = Donator.all
   @donators = @donators.search(params[:search]) if params[:search].present?
   respond_with(@donators)
  end

   private
    # Use callbacks to share common setup or constraints between actions.
    def set_donator
      @donator = Donator.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def donator_params
      params.require(:donator).permit(:nama, :kontak, :jenis_kelamin, :alamat)
    end
  
end

app/controllers/receivers_controller.rb
class ReceiversController < ApplicationController

	before_action :set_receiver, only: [:show, :edit, :update, :destroy, :change]

	respond_to :html

	def index
	 @receivers = Receiver.all
	 @receivers = @receivers.search(params[:search]) if params[:search].present?
	 respond_with(@receivers)
	end

	def show
		
	end

	def new
		@receiver = Receiver.new
    	respond_with(@receiver)
	end

	def create
		@receiver = Receiver.new(receiver_params)

	    @receiver.save
	    respond_with(@receiver)
	end

	def change
		@receiver.update_attributes(state: params[:state])
    	respond_to do |format|
      	format.html {redirect_to receivers_path, notice: "Mustahik Updated"}
    end
	end

	def update
		respond_to do |format|
      if @receiver.update(receiver_params)
        format.html { redirect_to @receiver, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @receiver }
      else
        format.html { render :edit }
        format.json { render json: @receiver.errors, status: :unprocessable_entity }
      end
    end
	end

	def edit
		
	end

	def delete
		
	end

	def destroy
		@receiver.destroy
   	 respond_to do |format|
      format.html { redirect_to receivers_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
	end

	private

		def set_receiver
	    
	      @receiver = Receiver.find(params[:id])

	    end


    # Never trust parameters from the scary internet, only allow the white list through.
		   def receiver_params
		     params.require(:receiver).permit(:nama, :jenis_kelamin, :tanggal_lahir, :alamat, :status)
		   end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donates_helper.rb
module DonatesHelper
end

app/helpers/donators_helper.rb
module DonatorsHelper
end

app/helpers/receivers_helper.rb
module ReceiversHelper
end

app/views/donates/_form.html.erb
<%= simple_form_for(@donate) do |f| %>

	Donatur : <%= f.collection_select :donator, Donator.all , :id, :nama, :prompt => "Pilih Donator" %>
	<%= f.input :tgl_donasi %>
	Bentuk Donasi : <%= f.input :dana, collection: ["dana", "barang"], as: :check_boxes %>
 	<%= f.input :besar_dana %>

 	<% for i in 0..9 do %>
  	<%= f.input :bentuk_barang[i] %>
	<% end %>
	

 	<%= f.button :submit, class: "btn btn-lg btn-primary btn-block" %>

<% end %>

app/views/donates/index.html.erb
<h1>Daftar Donasi</h1>



<%= form_tag receivers_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :nama => nil %>
  </p>
<% end %>



<table>
  <tr>
    <th>Tanggal Donasi</th>
    <th>Donatur</th>
    <th>Donasi </th>
    <th>Alamat</th>
    <th>Status</th>
    <th colspan="5"></th>
  </tr>

  <%= link_to 'Tambah Donasi', new_donate_path %>
</table>

app/views/donates/new.html.erb
<h1>Donasi #new</h1>
<p>Untuk halaman tambah donasi</p>

<%= render 'form', donate: @donate %>

<%= link_to 'Index', donates_path %>

app/views/donators/_form.html.erb
<%= simple_form_for(@donator) do |f| %>

	<%= f.input :nama %>
	<%= f.input :jenis_kelamin, collection: ["P", "L"], as: :radio_buttons %>
	<%= f.input :alamat, placeholder: "Alamat" %>
	<%= f.input :kontak %>
 	<%= f.button :submit, class: "btn btn-lg btn-primary btn-block" %>

<% end %>

app/views/donators/edit.html.erb
<h1 class="text-center">Editing Donator</h1>

<%= render 'form', donator: @donator %>

<%= link_to 'Show', @donator %> |
<%= link_to 'Back', donators_path %>

app/views/donators/home.html.erb
<h1>Donators#home</h1>
<p>Find me in app/views/donators/home.html.erb</p>

<h1><%= link_to 'Donatur', donators_path %></h1>
<h1><%= link_to 'Mustahik', receivers_path %></h1>
<h1><%= link_to 'Donasi', donates_path %></h1>

app/views/donators/index.html.erb
<h1>List Donator</h1>



<%= form_tag donators_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :nama => nil %>
  </p>
<% end %>


<table>
  <tr>
    <th>Nama</th>
    <th>Jenis Kelamin</th>
    <th>Alamat</th>
    <th>Kontak</th>
    <th colspan="4"></th>
  </tr>
 
  <% @donators.each do |donator| %>
    <tr>
      <td><%= donator.nama %></td>
      <td><%= donator.jenis_kelamin %></td>
      <td><%= donator.alamat %></td>
      <td><%= donator.kontak %></td>
      <td><%= link_to 'Show', donator_path(donator) %></td>
      <td><%= link_to 'Edit', edit_donator_path(donator) %></td>
      <td><%= link_to 'Destroy', donator_path(donator), method: :delete, data: {confirm: "Are you sure ? "} %></td>
    </tr>
  <% end %>

  <%= link_to 'Tambah Donator', new_path %>
</table>

app/views/donators/new.html.erb
<h1>Donators#new</h1>
<p>Untuk halaman tambah donatur</p>

<%= render 'form', donator: @donator %>

<%= link_to 'Index', donators_path %>

app/views/donators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nama :</strong>
  <%= @donator.nama %>
</p>

<p>
  <strong>Jenis Kelamin :</strong>
  <%= @donator.jenis_kelamin %>
</p>

<p>
  <strong>Alamat :</strong>
  <%= @donator.alamat %>
</p>

<p>
  <strong>No. Kontak :</strong>
  <%= @donator.kontak %>
</p>


<%= link_to 'Back', new_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Donateviewer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/receivers/_form.html.erb
<%= simple_form_for(@receiver) do |f| %>

	<%= f.input :nama %>
	<%= f.input :jenis_kelamin, collection: ["P", "L"], as: :radio_buttons %>
	Tanggal Lahir : <%= f.date_select :tanggal_lahir,start_year: Time.now.year - 90, end_year: Time.now.year, label: :tanggal_lahir %> 
	<%= f.input :alamat, placeholder: "Alamat" %>
	<%= f.input :status, collection: ["Yatim", "Piatu", "Yatim Piatu", "Dhuafa"], as: :radio_buttons %>
 	<%= f.button :submit, class: "btn btn-lg btn-primary btn-block" %>

<% end %>

app/views/receivers/edit.html.erb
<h1 class="text-center">Editing Mustahik</h1>

<%= render 'form', receiver: @receiver %>

<%= link_to 'Show', @receiver %> |
<%= link_to 'Back', receivers_path %>

app/views/receivers/index.html.erb
<h1>List Mustahik</h1>



<%= form_tag receivers_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :nama => nil %>
  </p>
<% end %>



<table>
  <tr>
    <th>Nama</th>
    <th>Jenis Kelamin</th>
    <th>Tanggal Lahir</th>
    <th>Alamat</th>
    <th>Status</th>
    <th colspan="5"></th>
  </tr>

 <% @receivers.each do |receiver| %>
    <tr>
      <td><%= receiver.nama %></td>
      <td><%= receiver.jenis_kelamin %></td>
      <td><%= receiver.tanggal_lahir %></td>
      <td><%= receiver.alamat %></td>
      <td><%= receiver.status %></td>
      <td><%= link_to 'Show', ''  %></td>
      <td><%= link_to 'Edit', edit_receiver_path(receiver) %></td>
      <td><%= link_to 'Destroy', receiver_path(receiver), method: :delete, data: {confirm: "Are you sure ? "} %></td>
    </tr>
  <% end %>
  <%= link_to 'Tambah Mustahik', new_receiver_path %>
</table>

app/views/receivers/new.html.erb
<h1>Mustahik #new</h1>
<p>Untuk halaman tambah mustahik</p>

<%= render 'form', receiver: @receiver %>

<%= link_to 'Index', donators_path %>

app/views/receivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nama :</strong>
  <%= @receiver.nama %>
</p>

<p>
  <strong>Jenis Kelamin :</strong>
  <%= @receiver.jenis_kelamin %>
</p>

<p>
  <strong>Tanggal Lahir :</strong>
  <%= @receiver.tanggal_lahir %>
</p>

<p>
  <strong>Alamat :</strong>
  <%= @receiver.alamat %>
</p>

<p>
  <strong>Status :</strong>
  <%= @receiver.status %>
</p>


<%= link_to 'Back', receivers_path %>